<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210217141542 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE apprenant_livrable_partiel_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE brief_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE brief_apprenant_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE brief_ma_promo_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE chat_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE commentaire_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE competence_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE competences_valides_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE etat_brief_groupe_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE filde_discussion_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE groupe_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE groupe_competence_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE groupe_tags_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE livrable_attendu_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE livrable_attendu_apprenant_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE livrable_partiel_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE niveau_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE profil_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE profil_sorti_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE promo_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE referenciel_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE refresh_tokens_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ressource_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tags_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE utilisateur_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE apprenant_livrable_partiel (id INT NOT NULL, apprenants_id INT DEFAULT NULL, livrable_partiels_id INT DEFAULT NULL, filde_discussion_id INT DEFAULT NULL, etat VARCHAR(255) NOT NULL, delai DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8572D6ADD4B7C9BD ON apprenant_livrable_partiel (apprenants_id)');
        $this->addSql('CREATE INDEX IDX_8572D6AD7B292AF4 ON apprenant_livrable_partiel (livrable_partiels_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8572D6AD2D916732 ON apprenant_livrable_partiel (filde_discussion_id)');
        $this->addSql('CREATE TABLE brief (id INT NOT NULL, formateurs_id INT DEFAULT NULL, langue VARCHAR(255) NOT NULL, nom_brief VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, critere_evaluation VARCHAR(255) NOT NULL, avatar BYTEA DEFAULT NULL, modalite_pedagogique VARCHAR(255) DEFAULT NULL, modalites_evaluation VARCHAR(255) DEFAULT NULL, status_brief VARCHAR(255) NOT NULL, status BOOLEAN DEFAULT NULL, etat VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1FBB1007FB0881C8 ON brief (formateurs_id)');
        $this->addSql('CREATE TABLE brief_tags (brief_id INT NOT NULL, tags_id INT NOT NULL, PRIMARY KEY(brief_id, tags_id))');
        $this->addSql('CREATE INDEX IDX_D4F170DD757FABFF ON brief_tags (brief_id)');
        $this->addSql('CREATE INDEX IDX_D4F170DD8D7B4FB4 ON brief_tags (tags_id)');
        $this->addSql('CREATE TABLE brief_niveau (brief_id INT NOT NULL, niveau_id INT NOT NULL, PRIMARY KEY(brief_id, niveau_id))');
        $this->addSql('CREATE INDEX IDX_1BF05631757FABFF ON brief_niveau (brief_id)');
        $this->addSql('CREATE INDEX IDX_1BF05631B3E9C81 ON brief_niveau (niveau_id)');
        $this->addSql('CREATE TABLE brief_apprenant (id INT NOT NULL, apprenants_id INT DEFAULT NULL, brief_ma_promo_id INT DEFAULT NULL, status BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DD6198EDD4B7C9BD ON brief_apprenant (apprenants_id)');
        $this->addSql('CREATE INDEX IDX_DD6198ED57574C78 ON brief_apprenant (brief_ma_promo_id)');
        $this->addSql('CREATE TABLE brief_ma_promo (id INT NOT NULL, briefs_id INT DEFAULT NULL, promo_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6E0C4800CA062D03 ON brief_ma_promo (briefs_id)');
        $this->addSql('CREATE INDEX IDX_6E0C4800D0C07AFF ON brief_ma_promo (promo_id)');
        $this->addSql('CREATE TABLE chat (id INT NOT NULL, users_id INT DEFAULT NULL, promo_id INT DEFAULT NULL, message TEXT NOT NULL, pieces_jointes BYTEA DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_659DF2AA67B3B43D ON chat (users_id)');
        $this->addSql('CREATE INDEX IDX_659DF2AAD0C07AFF ON chat (promo_id)');
        $this->addSql('CREATE TABLE commentaire (id INT NOT NULL, formateurs_id INT DEFAULT NULL, filde_discussion_id INT DEFAULT NULL, description VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_67F068BCFB0881C8 ON commentaire (formateurs_id)');
        $this->addSql('CREATE INDEX IDX_67F068BC2D916732 ON commentaire (filde_discussion_id)');
        $this->addSql('CREATE TABLE competence (id INT NOT NULL, libelle VARCHAR(255) NOT NULL, status BOOLEAN NOT NULL, descriptif VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE competences_valides (id INT NOT NULL, competences_id INT DEFAULT NULL, apprenants_id INT DEFAULT NULL, referenciels_id INT DEFAULT NULL, promo_id INT DEFAULT NULL, niveau1 BOOLEAN NOT NULL, niveau2 BOOLEAN NOT NULL, niveau3 BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9EEA096EA660B158 ON competences_valides (competences_id)');
        $this->addSql('CREATE INDEX IDX_9EEA096ED4B7C9BD ON competences_valides (apprenants_id)');
        $this->addSql('CREATE INDEX IDX_9EEA096ECE8A50AE ON competences_valides (referenciels_id)');
        $this->addSql('CREATE INDEX IDX_9EEA096ED0C07AFF ON competences_valides (promo_id)');
        $this->addSql('CREATE TABLE etat_brief_groupe (id INT NOT NULL, brief_id INT DEFAULT NULL, groupes_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4C4C1AA4757FABFF ON etat_brief_groupe (brief_id)');
        $this->addSql('CREATE INDEX IDX_4C4C1AA4305371B ON etat_brief_groupe (groupes_id)');
        $this->addSql('CREATE TABLE filde_discussion (id INT NOT NULL, titre VARCHAR(255) NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE groupe (id INT NOT NULL, nom_groupe VARCHAR(255) NOT NULL, status BOOLEAN NOT NULL, date_creation DATE NOT NULL, type VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE groupe_apprenant (groupe_id INT NOT NULL, apprenant_id INT NOT NULL, PRIMARY KEY(groupe_id, apprenant_id))');
        $this->addSql('CREATE INDEX IDX_947F95197A45358C ON groupe_apprenant (groupe_id)');
        $this->addSql('CREATE INDEX IDX_947F9519C5697D6D ON groupe_apprenant (apprenant_id)');
        $this->addSql('CREATE TABLE groupe_formateur (groupe_id INT NOT NULL, formateur_id INT NOT NULL, PRIMARY KEY(groupe_id, formateur_id))');
        $this->addSql('CREATE INDEX IDX_BDE2AD787A45358C ON groupe_formateur (groupe_id)');
        $this->addSql('CREATE INDEX IDX_BDE2AD78155D8F51 ON groupe_formateur (formateur_id)');
        $this->addSql('CREATE TABLE groupe_competence (id INT NOT NULL, libelle VARCHAR(255) NOT NULL, descriptif VARCHAR(255) NOT NULL, status BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE groupe_competence_competence (groupe_competence_id INT NOT NULL, competence_id INT NOT NULL, PRIMARY KEY(groupe_competence_id, competence_id))');
        $this->addSql('CREATE INDEX IDX_F64AE85C89034830 ON groupe_competence_competence (groupe_competence_id)');
        $this->addSql('CREATE INDEX IDX_F64AE85C15761DAB ON groupe_competence_competence (competence_id)');
        $this->addSql('CREATE TABLE groupe_tags (id INT NOT NULL, libelle VARCHAR(255) NOT NULL, status BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE groupe_tags_tags (groupe_tags_id INT NOT NULL, tags_id INT NOT NULL, PRIMARY KEY(groupe_tags_id, tags_id))');
        $this->addSql('CREATE INDEX IDX_308FEB414B1CA8FA ON groupe_tags_tags (groupe_tags_id)');
        $this->addSql('CREATE INDEX IDX_308FEB418D7B4FB4 ON groupe_tags_tags (tags_id)');
        $this->addSql('CREATE TABLE livrable_attendu (id INT NOT NULL, libelle VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, status BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE livrable_attendu_brief (livrable_attendu_id INT NOT NULL, brief_id INT NOT NULL, PRIMARY KEY(livrable_attendu_id, brief_id))');
        $this->addSql('CREATE INDEX IDX_778854ED75180ACC ON livrable_attendu_brief (livrable_attendu_id)');
        $this->addSql('CREATE INDEX IDX_778854ED757FABFF ON livrable_attendu_brief (brief_id)');
        $this->addSql('CREATE TABLE livrable_attendu_livrable_attendu_apprenant (livrable_attendu_id INT NOT NULL, livrable_attendu_apprenant_id INT NOT NULL, PRIMARY KEY(livrable_attendu_id, livrable_attendu_apprenant_id))');
        $this->addSql('CREATE INDEX IDX_300B551175180ACC ON livrable_attendu_livrable_attendu_apprenant (livrable_attendu_id)');
        $this->addSql('CREATE INDEX IDX_300B5511EE63D1F4 ON livrable_attendu_livrable_attendu_apprenant (livrable_attendu_apprenant_id)');
        $this->addSql('CREATE TABLE livrable_attendu_apprenant (id INT NOT NULL, apprenants_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BDB84E34D4B7C9BD ON livrable_attendu_apprenant (apprenants_id)');
        $this->addSql('CREATE TABLE livrable_partiel (id INT NOT NULL, brief_ma_promo_id INT DEFAULT NULL, libelle VARCHAR(255) NOT NULL, delai VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, nombre_rendu INT NOT NULL, description VARCHAR(255) NOT NULL, nombre_corrige INT NOT NULL, status BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_37F072C557574C78 ON livrable_partiel (brief_ma_promo_id)');
        $this->addSql('CREATE TABLE livrable_partiel_niveau (livrable_partiel_id INT NOT NULL, niveau_id INT NOT NULL, PRIMARY KEY(livrable_partiel_id, niveau_id))');
        $this->addSql('CREATE INDEX IDX_4FEB984B519178C4 ON livrable_partiel_niveau (livrable_partiel_id)');
        $this->addSql('CREATE INDEX IDX_4FEB984BB3E9C81 ON livrable_partiel_niveau (niveau_id)');
        $this->addSql('CREATE TABLE niveau (id INT NOT NULL, competence_id INT DEFAULT NULL, libelle VARCHAR(255) NOT NULL, critere_evalution VARCHAR(255) NOT NULL, groupe_action VARCHAR(255) NOT NULL, status BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4BDFF36B15761DAB ON niveau (competence_id)');
        $this->addSql('CREATE TABLE profil (id INT NOT NULL, libelle VARCHAR(255) NOT NULL, status BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE profil_sorti (id INT NOT NULL, libelle VARCHAR(255) NOT NULL, status BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE promo (id INT NOT NULL, nom_promo VARCHAR(255) NOT NULL, langue VARCHAR(255) NOT NULL, titre VARCHAR(255) NOT NULL, status BOOLEAN NOT NULL, description VARCHAR(255) NOT NULL, lieu VARCHAR(255) NOT NULL, date_fin_provisoire DATE NOT NULL, fabrique VARCHAR(255) NOT NULL, date_fin_reel DATE NOT NULL, avatar BYTEA DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE promo_groupe (promo_id INT NOT NULL, groupe_id INT NOT NULL, PRIMARY KEY(promo_id, groupe_id))');
        $this->addSql('CREATE INDEX IDX_1D3C936CD0C07AFF ON promo_groupe (promo_id)');
        $this->addSql('CREATE INDEX IDX_1D3C936C7A45358C ON promo_groupe (groupe_id)');
        $this->addSql('CREATE TABLE promo_referenciel (promo_id INT NOT NULL, referenciel_id INT NOT NULL, PRIMARY KEY(promo_id, referenciel_id))');
        $this->addSql('CREATE INDEX IDX_AE45E44DD0C07AFF ON promo_referenciel (promo_id)');
        $this->addSql('CREATE INDEX IDX_AE45E44D22241379 ON promo_referenciel (referenciel_id)');
        $this->addSql('CREATE TABLE referenciel (id INT NOT NULL, libelle VARCHAR(255) NOT NULL, presentation TEXT DEFAULT NULL, criteradmission TEXT DEFAULT NULL, critere_evaluation TEXT DEFAULT NULL, status BOOLEAN NOT NULL, programmes BYTEA DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE referenciel_groupe_competence (referenciel_id INT NOT NULL, groupe_competence_id INT NOT NULL, PRIMARY KEY(referenciel_id, groupe_competence_id))');
        $this->addSql('CREATE INDEX IDX_2016095A22241379 ON referenciel_groupe_competence (referenciel_id)');
        $this->addSql('CREATE INDEX IDX_2016095A89034830 ON referenciel_groupe_competence (groupe_competence_id)');
        $this->addSql('CREATE TABLE refresh_tokens (id INT NOT NULL, refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9BACE7E1C74F2195 ON refresh_tokens (refresh_token)');
        $this->addSql('CREATE TABLE ressource (id INT NOT NULL, briefs_id INT DEFAULT NULL, libelle VARCHAR(255) NOT NULL, delai DATE NOT NULL, description VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_939F4544CA062D03 ON ressource (briefs_id)');
        $this->addSql('CREATE TABLE tags (id INT NOT NULL, libelle VARCHAR(255) NOT NULL, descriptif VARCHAR(255) NOT NULL, status BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE utilisateur (id INT NOT NULL, profil_id INT DEFAULT NULL, profil_sorti_id INT DEFAULT NULL, promo_id INT DEFAULT NULL, username VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, nom_complete VARCHAR(255) NOT NULL, adresse VARCHAR(255) NOT NULL, telephone VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, status BOOLEAN DEFAULT NULL, avartar BYTEA DEFAULT NULL, genre VARCHAR(100) NOT NULL, type_id INT NOT NULL, attente BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1D1C63B3F85E0677 ON utilisateur (username)');
        $this->addSql('CREATE INDEX IDX_1D1C63B3275ED078 ON utilisateur (profil_id)');
        $this->addSql('CREATE INDEX IDX_1D1C63B3B37C4ED5 ON utilisateur (profil_sorti_id)');
        $this->addSql('CREATE INDEX IDX_1D1C63B3D0C07AFF ON utilisateur (promo_id)');
        $this->addSql('ALTER TABLE apprenant_livrable_partiel ADD CONSTRAINT FK_8572D6ADD4B7C9BD FOREIGN KEY (apprenants_id) REFERENCES utilisateur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE apprenant_livrable_partiel ADD CONSTRAINT FK_8572D6AD7B292AF4 FOREIGN KEY (livrable_partiels_id) REFERENCES livrable_partiel (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE apprenant_livrable_partiel ADD CONSTRAINT FK_8572D6AD2D916732 FOREIGN KEY (filde_discussion_id) REFERENCES filde_discussion (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE brief ADD CONSTRAINT FK_1FBB1007FB0881C8 FOREIGN KEY (formateurs_id) REFERENCES utilisateur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE brief_tags ADD CONSTRAINT FK_D4F170DD757FABFF FOREIGN KEY (brief_id) REFERENCES brief (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE brief_tags ADD CONSTRAINT FK_D4F170DD8D7B4FB4 FOREIGN KEY (tags_id) REFERENCES tags (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE brief_niveau ADD CONSTRAINT FK_1BF05631757FABFF FOREIGN KEY (brief_id) REFERENCES brief (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE brief_niveau ADD CONSTRAINT FK_1BF05631B3E9C81 FOREIGN KEY (niveau_id) REFERENCES niveau (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE brief_apprenant ADD CONSTRAINT FK_DD6198EDD4B7C9BD FOREIGN KEY (apprenants_id) REFERENCES utilisateur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE brief_apprenant ADD CONSTRAINT FK_DD6198ED57574C78 FOREIGN KEY (brief_ma_promo_id) REFERENCES brief_ma_promo (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE brief_ma_promo ADD CONSTRAINT FK_6E0C4800CA062D03 FOREIGN KEY (briefs_id) REFERENCES brief (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE brief_ma_promo ADD CONSTRAINT FK_6E0C4800D0C07AFF FOREIGN KEY (promo_id) REFERENCES promo (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE chat ADD CONSTRAINT FK_659DF2AA67B3B43D FOREIGN KEY (users_id) REFERENCES utilisateur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE chat ADD CONSTRAINT FK_659DF2AAD0C07AFF FOREIGN KEY (promo_id) REFERENCES promo (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT FK_67F068BCFB0881C8 FOREIGN KEY (formateurs_id) REFERENCES utilisateur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT FK_67F068BC2D916732 FOREIGN KEY (filde_discussion_id) REFERENCES filde_discussion (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE competences_valides ADD CONSTRAINT FK_9EEA096EA660B158 FOREIGN KEY (competences_id) REFERENCES competence (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE competences_valides ADD CONSTRAINT FK_9EEA096ED4B7C9BD FOREIGN KEY (apprenants_id) REFERENCES utilisateur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE competences_valides ADD CONSTRAINT FK_9EEA096ECE8A50AE FOREIGN KEY (referenciels_id) REFERENCES referenciel (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE competences_valides ADD CONSTRAINT FK_9EEA096ED0C07AFF FOREIGN KEY (promo_id) REFERENCES promo (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE etat_brief_groupe ADD CONSTRAINT FK_4C4C1AA4757FABFF FOREIGN KEY (brief_id) REFERENCES brief (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE etat_brief_groupe ADD CONSTRAINT FK_4C4C1AA4305371B FOREIGN KEY (groupes_id) REFERENCES groupe (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE groupe_apprenant ADD CONSTRAINT FK_947F95197A45358C FOREIGN KEY (groupe_id) REFERENCES groupe (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE groupe_apprenant ADD CONSTRAINT FK_947F9519C5697D6D FOREIGN KEY (apprenant_id) REFERENCES utilisateur (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE groupe_formateur ADD CONSTRAINT FK_BDE2AD787A45358C FOREIGN KEY (groupe_id) REFERENCES groupe (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE groupe_formateur ADD CONSTRAINT FK_BDE2AD78155D8F51 FOREIGN KEY (formateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE groupe_competence_competence ADD CONSTRAINT FK_F64AE85C89034830 FOREIGN KEY (groupe_competence_id) REFERENCES groupe_competence (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE groupe_competence_competence ADD CONSTRAINT FK_F64AE85C15761DAB FOREIGN KEY (competence_id) REFERENCES competence (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE groupe_tags_tags ADD CONSTRAINT FK_308FEB414B1CA8FA FOREIGN KEY (groupe_tags_id) REFERENCES groupe_tags (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE groupe_tags_tags ADD CONSTRAINT FK_308FEB418D7B4FB4 FOREIGN KEY (tags_id) REFERENCES tags (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE livrable_attendu_brief ADD CONSTRAINT FK_778854ED75180ACC FOREIGN KEY (livrable_attendu_id) REFERENCES livrable_attendu (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE livrable_attendu_brief ADD CONSTRAINT FK_778854ED757FABFF FOREIGN KEY (brief_id) REFERENCES brief (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE livrable_attendu_livrable_attendu_apprenant ADD CONSTRAINT FK_300B551175180ACC FOREIGN KEY (livrable_attendu_id) REFERENCES livrable_attendu (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE livrable_attendu_livrable_attendu_apprenant ADD CONSTRAINT FK_300B5511EE63D1F4 FOREIGN KEY (livrable_attendu_apprenant_id) REFERENCES livrable_attendu_apprenant (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE livrable_attendu_apprenant ADD CONSTRAINT FK_BDB84E34D4B7C9BD FOREIGN KEY (apprenants_id) REFERENCES utilisateur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE livrable_partiel ADD CONSTRAINT FK_37F072C557574C78 FOREIGN KEY (brief_ma_promo_id) REFERENCES brief_ma_promo (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE livrable_partiel_niveau ADD CONSTRAINT FK_4FEB984B519178C4 FOREIGN KEY (livrable_partiel_id) REFERENCES livrable_partiel (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE livrable_partiel_niveau ADD CONSTRAINT FK_4FEB984BB3E9C81 FOREIGN KEY (niveau_id) REFERENCES niveau (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE niveau ADD CONSTRAINT FK_4BDFF36B15761DAB FOREIGN KEY (competence_id) REFERENCES competence (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE promo_groupe ADD CONSTRAINT FK_1D3C936CD0C07AFF FOREIGN KEY (promo_id) REFERENCES promo (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE promo_groupe ADD CONSTRAINT FK_1D3C936C7A45358C FOREIGN KEY (groupe_id) REFERENCES groupe (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE promo_referenciel ADD CONSTRAINT FK_AE45E44DD0C07AFF FOREIGN KEY (promo_id) REFERENCES promo (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE promo_referenciel ADD CONSTRAINT FK_AE45E44D22241379 FOREIGN KEY (referenciel_id) REFERENCES referenciel (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE referenciel_groupe_competence ADD CONSTRAINT FK_2016095A22241379 FOREIGN KEY (referenciel_id) REFERENCES referenciel (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE referenciel_groupe_competence ADD CONSTRAINT FK_2016095A89034830 FOREIGN KEY (groupe_competence_id) REFERENCES groupe_competence (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ressource ADD CONSTRAINT FK_939F4544CA062D03 FOREIGN KEY (briefs_id) REFERENCES brief (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE utilisateur ADD CONSTRAINT FK_1D1C63B3275ED078 FOREIGN KEY (profil_id) REFERENCES profil (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE utilisateur ADD CONSTRAINT FK_1D1C63B3B37C4ED5 FOREIGN KEY (profil_sorti_id) REFERENCES profil_sorti (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE utilisateur ADD CONSTRAINT FK_1D1C63B3D0C07AFF FOREIGN KEY (promo_id) REFERENCES promo (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE brief_tags DROP CONSTRAINT FK_D4F170DD757FABFF');
        $this->addSql('ALTER TABLE brief_niveau DROP CONSTRAINT FK_1BF05631757FABFF');
        $this->addSql('ALTER TABLE brief_ma_promo DROP CONSTRAINT FK_6E0C4800CA062D03');
        $this->addSql('ALTER TABLE etat_brief_groupe DROP CONSTRAINT FK_4C4C1AA4757FABFF');
        $this->addSql('ALTER TABLE livrable_attendu_brief DROP CONSTRAINT FK_778854ED757FABFF');
        $this->addSql('ALTER TABLE ressource DROP CONSTRAINT FK_939F4544CA062D03');
        $this->addSql('ALTER TABLE brief_apprenant DROP CONSTRAINT FK_DD6198ED57574C78');
        $this->addSql('ALTER TABLE livrable_partiel DROP CONSTRAINT FK_37F072C557574C78');
        $this->addSql('ALTER TABLE competences_valides DROP CONSTRAINT FK_9EEA096EA660B158');
        $this->addSql('ALTER TABLE groupe_competence_competence DROP CONSTRAINT FK_F64AE85C15761DAB');
        $this->addSql('ALTER TABLE niveau DROP CONSTRAINT FK_4BDFF36B15761DAB');
        $this->addSql('ALTER TABLE apprenant_livrable_partiel DROP CONSTRAINT FK_8572D6AD2D916732');
        $this->addSql('ALTER TABLE commentaire DROP CONSTRAINT FK_67F068BC2D916732');
        $this->addSql('ALTER TABLE etat_brief_groupe DROP CONSTRAINT FK_4C4C1AA4305371B');
        $this->addSql('ALTER TABLE groupe_apprenant DROP CONSTRAINT FK_947F95197A45358C');
        $this->addSql('ALTER TABLE groupe_formateur DROP CONSTRAINT FK_BDE2AD787A45358C');
        $this->addSql('ALTER TABLE promo_groupe DROP CONSTRAINT FK_1D3C936C7A45358C');
        $this->addSql('ALTER TABLE groupe_competence_competence DROP CONSTRAINT FK_F64AE85C89034830');
        $this->addSql('ALTER TABLE referenciel_groupe_competence DROP CONSTRAINT FK_2016095A89034830');
        $this->addSql('ALTER TABLE groupe_tags_tags DROP CONSTRAINT FK_308FEB414B1CA8FA');
        $this->addSql('ALTER TABLE livrable_attendu_brief DROP CONSTRAINT FK_778854ED75180ACC');
        $this->addSql('ALTER TABLE livrable_attendu_livrable_attendu_apprenant DROP CONSTRAINT FK_300B551175180ACC');
        $this->addSql('ALTER TABLE livrable_attendu_livrable_attendu_apprenant DROP CONSTRAINT FK_300B5511EE63D1F4');
        $this->addSql('ALTER TABLE apprenant_livrable_partiel DROP CONSTRAINT FK_8572D6AD7B292AF4');
        $this->addSql('ALTER TABLE livrable_partiel_niveau DROP CONSTRAINT FK_4FEB984B519178C4');
        $this->addSql('ALTER TABLE brief_niveau DROP CONSTRAINT FK_1BF05631B3E9C81');
        $this->addSql('ALTER TABLE livrable_partiel_niveau DROP CONSTRAINT FK_4FEB984BB3E9C81');
        $this->addSql('ALTER TABLE utilisateur DROP CONSTRAINT FK_1D1C63B3275ED078');
        $this->addSql('ALTER TABLE utilisateur DROP CONSTRAINT FK_1D1C63B3B37C4ED5');
        $this->addSql('ALTER TABLE brief_ma_promo DROP CONSTRAINT FK_6E0C4800D0C07AFF');
        $this->addSql('ALTER TABLE chat DROP CONSTRAINT FK_659DF2AAD0C07AFF');
        $this->addSql('ALTER TABLE competences_valides DROP CONSTRAINT FK_9EEA096ED0C07AFF');
        $this->addSql('ALTER TABLE promo_groupe DROP CONSTRAINT FK_1D3C936CD0C07AFF');
        $this->addSql('ALTER TABLE promo_referenciel DROP CONSTRAINT FK_AE45E44DD0C07AFF');
        $this->addSql('ALTER TABLE utilisateur DROP CONSTRAINT FK_1D1C63B3D0C07AFF');
        $this->addSql('ALTER TABLE competences_valides DROP CONSTRAINT FK_9EEA096ECE8A50AE');
        $this->addSql('ALTER TABLE promo_referenciel DROP CONSTRAINT FK_AE45E44D22241379');
        $this->addSql('ALTER TABLE referenciel_groupe_competence DROP CONSTRAINT FK_2016095A22241379');
        $this->addSql('ALTER TABLE brief_tags DROP CONSTRAINT FK_D4F170DD8D7B4FB4');
        $this->addSql('ALTER TABLE groupe_tags_tags DROP CONSTRAINT FK_308FEB418D7B4FB4');
        $this->addSql('ALTER TABLE apprenant_livrable_partiel DROP CONSTRAINT FK_8572D6ADD4B7C9BD');
        $this->addSql('ALTER TABLE brief DROP CONSTRAINT FK_1FBB1007FB0881C8');
        $this->addSql('ALTER TABLE brief_apprenant DROP CONSTRAINT FK_DD6198EDD4B7C9BD');
        $this->addSql('ALTER TABLE chat DROP CONSTRAINT FK_659DF2AA67B3B43D');
        $this->addSql('ALTER TABLE commentaire DROP CONSTRAINT FK_67F068BCFB0881C8');
        $this->addSql('ALTER TABLE competences_valides DROP CONSTRAINT FK_9EEA096ED4B7C9BD');
        $this->addSql('ALTER TABLE groupe_apprenant DROP CONSTRAINT FK_947F9519C5697D6D');
        $this->addSql('ALTER TABLE groupe_formateur DROP CONSTRAINT FK_BDE2AD78155D8F51');
        $this->addSql('ALTER TABLE livrable_attendu_apprenant DROP CONSTRAINT FK_BDB84E34D4B7C9BD');
        $this->addSql('DROP SEQUENCE apprenant_livrable_partiel_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE brief_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE brief_apprenant_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE brief_ma_promo_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE chat_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE commentaire_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE competence_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE competences_valides_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE etat_brief_groupe_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE filde_discussion_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE groupe_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE groupe_competence_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE groupe_tags_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE livrable_attendu_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE livrable_attendu_apprenant_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE livrable_partiel_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE niveau_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE profil_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE profil_sorti_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE promo_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE referenciel_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE refresh_tokens_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ressource_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tags_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE utilisateur_id_seq CASCADE');
        $this->addSql('DROP TABLE apprenant_livrable_partiel');
        $this->addSql('DROP TABLE brief');
        $this->addSql('DROP TABLE brief_tags');
        $this->addSql('DROP TABLE brief_niveau');
        $this->addSql('DROP TABLE brief_apprenant');
        $this->addSql('DROP TABLE brief_ma_promo');
        $this->addSql('DROP TABLE chat');
        $this->addSql('DROP TABLE commentaire');
        $this->addSql('DROP TABLE competence');
        $this->addSql('DROP TABLE competences_valides');
        $this->addSql('DROP TABLE etat_brief_groupe');
        $this->addSql('DROP TABLE filde_discussion');
        $this->addSql('DROP TABLE groupe');
        $this->addSql('DROP TABLE groupe_apprenant');
        $this->addSql('DROP TABLE groupe_formateur');
        $this->addSql('DROP TABLE groupe_competence');
        $this->addSql('DROP TABLE groupe_competence_competence');
        $this->addSql('DROP TABLE groupe_tags');
        $this->addSql('DROP TABLE groupe_tags_tags');
        $this->addSql('DROP TABLE livrable_attendu');
        $this->addSql('DROP TABLE livrable_attendu_brief');
        $this->addSql('DROP TABLE livrable_attendu_livrable_attendu_apprenant');
        $this->addSql('DROP TABLE livrable_attendu_apprenant');
        $this->addSql('DROP TABLE livrable_partiel');
        $this->addSql('DROP TABLE livrable_partiel_niveau');
        $this->addSql('DROP TABLE niveau');
        $this->addSql('DROP TABLE profil');
        $this->addSql('DROP TABLE profil_sorti');
        $this->addSql('DROP TABLE promo');
        $this->addSql('DROP TABLE promo_groupe');
        $this->addSql('DROP TABLE promo_referenciel');
        $this->addSql('DROP TABLE referenciel');
        $this->addSql('DROP TABLE referenciel_groupe_competence');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE ressource');
        $this->addSql('DROP TABLE tags');
        $this->addSql('DROP TABLE utilisateur');
    }
}
